//登录相关
export const Login = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGIN_FIELD_CHANGE: 'LOGIN_FIELD_CHANGE',
    LOGIN_FIELD_RESET: 'LOGIN_FIELD_RESET',
}

//首页相关
export const HomePage = {
    CHANGE_COLLAPSED: "CHANGE_COLLAPSED",
    SELECT_MENU_SUCCESS: "SELECT_MENU_SUCCESS",
}

//默认首页相关
export const DefaultPage = {
    DEFAULT_PAGE_SET_LOCALIP: "DEFAULT_PAGE_SET_LOCALIP",
    DEFAULT_SET_SERVER_STATUS: "DEFAULT_SET_SERVER_STATUS",
    DEFAULT_INIT_SERVER: "DEFAULT_INIT_SERVER",
    DEFAULT_STOP_SERVER: "DEFAULT_STOP_SERVER",
    DEFAULT_SEND_LOGINFO: "DEFAULT_SEND_LOGINFO",
}

//桌台相关
export const Table = {
    QUERY_TABLE_PENDING: "QUERY_TABLE_PENDING",
    QUERY_TABLE_SUCCESS: "QUERY_TABLE_SUCCESS",
    QUERY_TABLE_FAILURE: "QUERY_TABLE_FAILURE",
}

//基础配置相关
export const BasicConfig = {
    SELECT_BASIC_CONFIG_PENDING: "SELECT_BASIC_CONFIG_PENDING",
    SELECT_BASIC_CONFIG_SUCCESS: "SELECT_BASIC_CONFIG_SUCCESS",
    SELECT_BASIC_CONFIG_FAILURE: "SELECT_BASIC_CONFIG_FAILURE",
}

//后厨页
export const Monitor = {
    SELECT_PLACEORDER_PENDING: "SELECT_PLACEORDER_PENDING",
    SELECT_PLACEORDER_SUCCESS: 'SELECT_PLACEORDER_SUCCESS',
    SELECT_PLACEORDER_FAILURE: "SELECT_PLACEORDER_FAILURE",
}