//登录相关
export const Login = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGOUT: 'LOGOUT',
    MODIFY_PWD_PENDING: "MODIFY_PWD_PENDING",
    MODIFY_PWD_SUCCESS: "MODIFY_PWD_SUCCESS",
    MODIFY_PWD_FAILURE: "MODIFY_PWD_FAILURE",
}
//首页相关
export const Home = {
    TODAY_RULE_PENDING: 'TODAY_RULE_PENDING',
    TODAY_RULE_SUCCESS: 'TODAY_RULE_SUCCESS',
    TODAY_RULE_FAILURE: "TODAY_RULE_FAILURE",
    DISPATCH_SOCKETSTATUS_SUCCESS: "DISPATCH_SOCKETSTATUS_SUCCESS",
    SELECT_CURRENT_MERCHANT_PENDING: "SELECT_CURRENT_MERCHANT_PENDING",
    SELECT_CURRENT_MERCHANT_SUCCESS: "SELECT_CURRENT_MERCHANT_SUCCESS",
    SELECT_CURRENT_MERCHANT_FAILURE: "SELECT_CURRENT_MERCHANT_FAILURE",
}
//桌台相关
export const Table = {
    DISPATCH_FLOORS_SUCCESS: "DISPATCH_FLOORS_SUCCESS",
    DISPATCH_TABLES_SUCCESS: "DISPATCH_TABLES_SUCCESS",
    DISPATCH_TABLESTATUS_SUCCESS: "DISPATCH_TABLESTATUS_SUCCESS",
}
//下单
export const PlaceOrder = {
    LIST_GOODSDAYSDISCOUNT_PENDING: 'LIST_GOODSDAYSDISCOUNT_PENDING',
    LIST_GOODSDAYSDISCOUNT_SUCCESS: 'LIST_GOODSDAYSDISCOUNT_SUCCESS',
    LIST_GOODSDAYSDISCOUNT_FAILURE: 'LIST_GOODSDAYSDISCOUNT_FAILURE',
    CHECKED_GOODS_EXTRAITEM_SUCCESS: 'CHECKED_GOODS_EXTRAITEM_SUCCESS',
    DISPATCH_GOODSEXTRA_SUCCESS: 'DISPATCH_GOODSEXTRA_SUCCESS',
    DISPATCH_GOODSEXTRAS_SUCCESS: 'DISPATCH_GOODSEXTRAS_SUCCESS',
    SUBMIT_ORDER_PENDING: "SUBMIT_ORDER_PENDING",
    SUBMIT_ORDER_SUCCESS: "SUBMIT_ORDER_SUCCESS",
    SUBMIT_ORDER_FAILURE: "SUBMIT_ORDER_FAILURE",
    LIST_CURRENT_SUBTRACT_SUCCESS: "LIST_CURRENT_SUBTRACT_SUCCESS",
}

//订单
export const Order = {
    SELECT_ORDER_PENDING: "SELECT_ORDER_PENDING",
    SELECT_ORDER_SUCCESS: "SELECT_ORDER_SUCCESS",
    SELECT_ORDER_FAILURE: "SELECT_ORDER_FAILURE",
    ORDERDETAIL_DELETE_ORDERITEM_PENDING: "ORDERDETAIL_DELETE_ORDERITEM_PENDING",
    ORDERDETAIL_DELETE_ORDERITEM_SUCCESS: "ORDERDETAIL_DELETE_ORDERITEM_SUCCESS",
    ORDERDETAIL_DELETE_ORDERITEM_FAILURE: "ORDERDETAIL_DELETE_ORDERITEM_FAILURE",
    ORDERDETAIL_CANCEL_ORDERITEM_PENDING: "ORDERDETAIL_CANCEL_ORDERITEM_PENDING",
    ORDERDETAIL_CANCEL_ORDERITEM_SUCCESS: "ORDERDETAIL_CANCEL_ORDERITEM_SUCCESS",
    ORDERDETAIL_CANCEL_ORDERITEM_FAILURE: "ORDERDETAIL_CANCEL_ORDERITEM_FAILURE",
    ORDERDETAIL_SHIPPED_ORDERITEM_PENDING: "ORDERDETAIL_SHIPPED_ORDERITEM_PENDING",
    ORDERDETAIL_SHIPPED_ORDERITEM_SUCCESS: "ORDERDETAIL_SHIPPED_ORDERITEM_SUCCESS",
    ORDERDETAIL_SHIPPED_ORDERITEM_FAILURE: "ORDERDETAIL_SHIPPED_ORDERITEM_FAILURE",
    ORDERDETAIL_RECEIVE_ORDERITEM_PENDING: "ORDERDETAIL_RECEIVE_ORDERITEM_PENDING",
    ORDERDETAIL_RECEIVE_ORDERITEM_SUCCESS: "ORDERDETAIL_RECEIVE_ORDERITEM_SUCCESS",
    ORDERDETAIL_RECEIVE_ORDERITEM_FAILURE: "ORDERDETAIL_RECEIVE_ORDERITEM_FAILURE",
    CONFIRM_ORDERITEM_PENDING: "CONFIRM_ORDERITEM_PENDING",
    CONFIRM_ORDERITEM_SUCCESS: "CONFIRM_ORDERITEM_SUCCESS",
    CONFIRM_ORDERITEM_FAILURE: "CONFIRM_ORDERITEM_FAILURE",
    CONFIRM_ORDER_PENDING: "CONFIRM_ORDER_PENDING",
    CONFIRM_ORDER_SUCCESS: "CONFIRM_ORDER_SUCCESS",
    CONFIRM_ORDER_FAILURE: "CONFIRM_ORDER_FAILURE",
    CHANGE_TABLECODE_PENDING: "CHANGE_TABLECODE_PENDING",
    CHANGE_TABLECODE_SUCCESS: "CHANGE_TABLECODE_SUCCESS",
    CHANGE_TABLECODE_FAILURE: "CHANGE_TABLECODE_FAILURE",
    FINISHED_ORDER_SUCCESS: "FINISHED_ORDER_SUCCESS",
}

export const Profile = {
    SELECT_LASTVERSION_PENDING: "SELECT_LASTVERSION_PENDING",
    SELECT_LASTVERSION_SUCCESS: "SELECT_LASTVERSION_SUCCESS",
    SELECT_LASTVERSION_FAILURE: "SELECT_LASTVERSION_FAILURE",
    DISPATCH_VERSIONNAME_SUCCESS: "DISPATCH_VERSIONNAME_SUCCESS",
}