//登录相关
export const Login = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGIN_FIELD_CHANGE: 'LOGIN_FIELD_CHANGE',
    LOGIN_FIELD_RESET: 'LOGIN_FIELD_RESET',
}

//首页相关
export const HomePage = {
    CHANGE_COLLAPSED: "CHANGE_COLLAPSED",
    SELECT_MENU_SUCCESS: "SELECT_MENU_SUCCESS",
    GET_LAST_VERSION_PENDING: "GET_LAST_VERSION_PENDING",
    GET_LAST_VERSION_SUCCESS: "GET_LAST_VERSION_SUCCESS",
    GET_LAST_VERSION_FAILURE: "GET_LAST_VERSION_FAILURE",
    SELECT_CURRENT_MERCHANT_PENDING: "SELECT_CURRENT_MERCHANT_PENDING",
    SELECT_CURRENT_MERCHANT_SUCCESS: "SELECT_CURRENT_MERCHANT_SUCCESS",
    SELECT_CURRENT_MERCHANT_FAILURE: "SELECT_CURRENT_MERCHANT_FAILURE",
}

//排队相关
export const Queue = {
    QUERY_QUEUE_PENDING: "QUERY_QUEUE_PENDING",
    QUERY_QUEUE_SUCCESS: "QUERY_QUEUE_SUCCESS",
    QUERY_QUEUE_FAILURE: "QUERY_QUEUE_FAILURE",
    SAVE_QUEUE_PENDING: "SAVE_QUEUE_PENDING",
    SAVE_QUEUE_SUCCESS: "SAVE_QUEUE_SUCCESS",
    SAVE_QUEUE_FAILURE: "SAVE_QUEUE_FAILURE",
    UPDATE_QUEUE_PENDING: "UPDATE_QUEUE_PENDING",
    UPDATE_QUEUE_SUCCESS: "UPDATE_QUEUE_SUCCESS",
    UPDATE_QUEUE_FAILURE: "UPDATE_QUEUE_FAILURE",
    DELETE_QUEUE_PENDING: "DELETE_QUEUE_PENDING",
    DELETE_QUEUE_SUCCESS: "DELETE_QUEUE_SUCCESS",
    DELETE_QUEUE_FAILURE: "DELETE_QUEUE_FAILURE",
    SELECT_QUEUE_PENDING: "SELECT_QUEUE_PENDING",
    SELECT_QUEUE_SUCCESS: "SELECT_QUEUE_SUCCESS",
    SELECT_QUEUE_FAILURE: "SELECT_QUEUE_FAILURE",
    CREATE_QUEUE_FIELD_CHANGE: "CREATE_QUEUE_FIELD_CHANGE",
    CREATE_QUEUE_FIELD_RESET: "CREATE_QUEUE_FIELD_RESET",

    QUERY_QUEUEELEMENT_SUCCESS: "QUERY_QUEUEELEMENT_SUCCESS",
    SAVE_QUEUEELEMENT_SUCCESS: "SAVE_QUEUEELEMENT_SUCCESS",
    UPDATE_QUEUEELEMENT_SUCCESS: "UPDATE_QUEUEELEMENT_SUCCESS",

    QUEUE_TABLE_GRAG_GRDOP: "QUEUE_TABLE_GRAG_GRDOP",
    CREATE_QUEUE_ELEMENT_FIELD_CHANGE: "CREATE_QUEUE_ELEMENT_FIELD_CHANGE",
    CREATE_QUEUE_ELEMENT_FIELD_RESET: "CREATE_QUEUE_ELEMENT_FIELD_RESET",
    INIT_QUEUE_ELEMENT_FIELD: "INIT_QUEUE_ELEMENT_FIELD",
    SELECT_QUEUE_ELEMENT_SUCCESS: "SELECT_QUEUE_ELEMENT_SUCCESS",
    UPDATE_QUEUEELEMENT_SUCCESS_2: "UPDATE_QUEUEELEMENT_SUCCESS_2",
    UPDATE_TABLE_STATUS_SUCCESS: "UPDATE_TABLE_STATUS_SUCCESS",

    DELETE_QUEUE_ELEMENT_SUCCESS: "DELETE_QUEUE_ELEMENT_SUCCESS",
}

//桌台相关
export const Table = {
    QUERY_TABLE_PENDING: "QUERY_TABLE_PENDING",
    QUERY_TABLE_SUCCESS: "QUERY_TABLE_SUCCESS",
    QUERY_TABLE_FAILURE: "QUERY_TABLE_FAILURE",
}

//基础配置相关
export const BasicConfig = {
    SELECT_BASIC_CONFIG_PENDING: "SELECT_BASIC_CONFIG_PENDING",
    SELECT_BASIC_CONFIG_SUCCESS: "SELECT_BASIC_CONFIG_SUCCESS",
    SELECT_BASIC_CONFIG_FAILURE: "SELECT_BASIC_CONFIG_FAILURE",
}