//登录相关
export const Login = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGOUT: 'LOGOUT',
}

//首页相关
export const HomePage = {
    CHANGE_COLLAPSED: "CHANGE_COLLAPSED",
}

//产品分类相关
export const GoodsCategory = {
    QUERY_CATEGORY_PENDING: "QUERY_CATEGORY_PENDING",
    QUERY_CATEGORY_SUCCESS: "QUERY_CATEGORY_SUCCESS",
    QUERY_CATEGORY_FAILURE: "QUERY_CATEGORY_FAILURE",
    ADD_CATEGORY_PENDING: "ADD_CATEGORY_PENDING",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    UPDATE_CATEGORY_PENDING: "UPDATE_CATEGORY_PENDING",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
    DELETE_CATEGORY_PENDING: "DELETE_CATEGORY_PENDING",
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
}

//字典
export const Dictionary = {
    QUERY_DICTIONARY_PENDING: "QUERY_DICTIONARY_PENDING",
    QUERY_DICTIONARY_SUCCESS: "QUERY_DICTIONARY_SUCCESS",
    QUERY_DICTIONARY_FAILURE: "QUERY_DICTIONARY_FAILURE",
    ADD_DICTIONARY_PENDING: "ADD_DICTIONARY_PENDING",
    ADD_DICTIONARY_SUCCESS: "ADD_DICTIONARY_SUCCESS",
    ADD_DICTIONARY_FAILURE: "ADD_DICTIONARY_FAILURE",
    DELETE_DICTIONARY_PENDING: "DELETE_DICTIONARY_PENDING",
    DELETE_DICTIONARY_SUCCESS: "DELETE_DICTIONARY_SUCCESS",
    DELETE_DICTIONARY_FAILURE: "DELETE_DICTIONARY_FAILURE",
    UPDATE_DICTIONARY_PENDING: "UPDATE_DICTIONARY_PENDING",
    UPDATE_DICTIONARY_SUCCESS: "UPDATE_DICTIONARY_SUCCESS",
    UPDATE_DICTIONARY_FAILURE: "UPDATE_DICTIONARY_FAILURE",
    CREATE_FIELD_CHANGE: "CREATE_FIELD_CHANGE",
    SELECT_DICTIONARY_SUCCESS: "SELECT_DICTIONARY_SUCCESS",
    SELECT_ITEMS_PENDING: "SELECT_ITEMS_PENDING",
    SELECT_ITEMS_SUCCESS: "SELECT_ITEMS_SUCCESS",
    SELECT_ITEMS_FAILURE: "SELECT_ITEMS_FAILURE",
    ADD_ITEM_ROW: "ADD_ITEM_ROW",
    REMOVE_ITEM_ROW: "REMOVE_ITEM_ROW",
    ADD_ITEM_PENDING: "ADD_ITEM_PENDING",
    ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
    ADD_ITEM_FAILURE: "ADD_ITEM_FAILURE",
    UPDATE_ITEM_PENDING: "UPDATE_ITEM_PENDING",
    UPDATE_ITEM_SUCCESS: "UPDATE_ITEM_SUCCESS",
    UPDATE_ITEM_FAILURE: "UPDATE_ITEM_FAILURE",
    DELETE_ITEM_PENDING: "DELETE_ITEM_PENDING",
    DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",
    DELETE_ITEM_FAILURE: "DELETE_ITEM_FAILURE",
}

//功能菜单
export const MenuFunc = {
    LIST_FUNC_TREE_PENDING: "LIST_FUNC_TREE_PENDING",
    LIST_FUNC_TREE_SUCCESS: "LIST_FUNC_TREE_SUCCESS",
    LIST_FUNC_TREE_FAILURE: "LIST_FUNC_TREE_FAILURE",
    FIELD_CHANGE: "FIELD_CHANGE",
    ADD_FUNCTION: "ADD_FUNCTION",
    SAVE_FUNCTION_PENDING: "SAVE_FUNCTION_PENDING",
    SAVE_FUNCTION_SUCCESS: "SAVE_FUNCTION_SUCCESS",
    SAVE_FUNCTION_FAILURE: "SAVE_FUNCTION_FAILURE",
    SELECT_FUNCTION_PENDING: "SELECT_FUNCTION_PENDING",
    SELECT_FUNCTION_SUCCESS: "SELECT_FUNCTION_SUCCESS",
    SELECT_FUNCTION_FAILURE: "SELECT_FUNCTION_FAILURE",
    UPDATE_FUNCTION_PENDING: "UPDATE_FUNCTION_PENDING",
    UPDATE_FUNCTION_SUCCESS: "UPDATE_FUNCTION_SUCCESS",
    UPDATE_FUNCTION_FAILURE: "UPDATE_FUNCTION_FAILURE",
    DELETE_FUNCTION_SUCCESS: "DELETE_FUNCTION_SUCCESS",
    LIST_DICTITEMS_SUCCESS: "LIST_DICTITEMS_SUCCESS",
}

//审核商家
export const CheckMerchant = {
    SELECT_CHECKMERCHANT_PENDING: "SELECT_CHECKMERCHANT_PENDING",
    SELECT_CHECKMERCHANT_SUCCESS: "SELECT_CHECKMERCHANT_SUCCESS",
    SELECT_CHECKMERCHANT_FAILURE: "SELECT_CHECKMERCHANT_FAILURE",
    SELECT_MERCHANT_DETAIL_PENDING: "SELECT_MERCHANT_DETAIL_PENDING",
    SELECT_MERCHANT_DETAIL_SUCCESS: "SELECT_MERCHANT_DETAIL_SUCCESS",
    SELECT_MERCHANT_DETAIL_FAILURE: "SELECT_MERCHANT_DETAIL_FAILURE",
    GET_LONLAT_SUCCESS: "GET_LONLAT_SUCCESS",
    CHECK_MERCHANT_DETAIL_PENDING: "CHECK_MERCHANT_DETAIL_PENDING",
    CHECK_MERCHANT_DETAIL_SUCCESS: "CHECK_MERCHANT_DETAIL_SUCCESS",
    CHECK_MERCHANT_DETAIL_FAILURE: "CHECK_MERCHANT_DETAIL_FAILURE",
    LIST_AUDIT_HIS_SUCCESS: "LIST_AUDIT_HIS_SUCCESS",
    GET_MERCHANT_YYZZ_IMAGE: "GET_MERCHANT_YYZZ_IMAGE",
    LIST_USERCHANGE_HIS_SUCCESS: "LIST_USERCHANGE_HIS_SUCCESS",
    CHECK_MERCHANT_CHANGE_PENDING: "CHECK_MERCHANT_CHANGE_PENDING",
    CHECK_MERCHANT_CHANGE_SUCCESS: "CHECK_MERCHANT_CHANGE_SUCCESS",
    CHECK_MERCHANT_CHANGE_FAILURE: "CHECK_MERCHANT_CHANGE_FAILURE",
}